# Generated by Django 4.0.3 on 2022-04-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoraSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.TextField(blank=True, max_length=50, verbose_name='Matricula Alumno')),
                ('nombre', models.TextField(blank=True, max_length=50, verbose_name='Nombre Alumno')),
                ('sala', models.CharField(blank=True, max_length=50, verbose_name='Sala Alumno')),
                ('hora', models.CharField(blank=True, max_length=50, verbose_name='Hora Alumno')),
            ],
        ),
    ]
